"""
PBIP Generator — generates a complete Power BI Project folder structure.

Output:
    {ProjectName}.pbip
    {ProjectName}.SemanticModel/
        definition/
            model.tmdl
            tables/
                {TableName}.tmdl
                _Measures.tmdl
            relationships.tmdl
        definition.pbism
    {ProjectName}.Report/
        definition/
            report.json
        definition.pbir
"""
import json
import re
from pathlib import Path
from typing import Dict, List, Any
from loguru import logger


class PBIPGenerator:
    """Generate a complete Power BI Project (PBIP) folder structure."""

    DATA_TYPE_MAP = {
        "VARCHAR": "string", "CHAR": "string", "TEXT": "string", "STRING": "string",
        "INT32": "int64", "INT64": "int64", "INTEGER": "int64", "INT": "int64",
        "DOUBLE": "double", "FLOAT": "double", "DECIMAL": "double", "REAL": "double",
        "BOOL": "boolean", "BOOLEAN": "boolean",
        "DATE": "dateTime", "DATETIME": "dateTime", "TIMESTAMP": "dateTime", "TIME": "dateTime",
        "string": "string", "real": "double", "": "string",
    }

    CARDINALITY_MAP = {
        "many-to-one": "manyToOne", "many_to_one": "manyToOne",
        "one-to-one": "oneToOne", "one_to_one": "oneToOne",
        "many-to-many": "manyToMany", "many_to_many": "manyToMany",
        "one-to-many": "oneToMany", "one_to_many": "oneToMany",
    }

    CROSSFILTER_MAP = {
        "INNER": "bothDirections", "LEFT_OUTER": "oneDirection",
        "RIGHT_OUTER": "oneDirection", "FULL_OUTER": "bothDirections",
    }

    AGGREGATION_MAP = {
        "sum": "sum",
        "avg": "average",
        "average": "average",
        "min": "min",
        "max": "max",
        "count": "count",
        "count_distinct": "distinctCount",
        "distinctcount": "distinctCount",
        "distinct_count": "distinctCount",
        "unique_count": "distinctCount",
        "none": "none",
    }

    def __init__(self, project_name: str, output_dir: str):
        self.project_name = re.sub(r"[^\w\-]", "_", project_name)
        self.output_dir = Path(output_dir)
        self.semantic_dir = self.output_dir / f"{self.project_name}.SemanticModel" / "definition"
        self.tables_dir = self.semantic_dir / "tables"
        self.report_dir = self.output_dir / f"{self.project_name}.Report" / "definition"

    def generate(self, intermediate_model: Dict[str, Any], dax_conversions: List[Dict[str, Any]]) -> Path:
        """Generate the complete PBIP project. Returns path to project root."""
        self.tables_dir.mkdir(parents=True, exist_ok=True)
        self.report_dir.mkdir(parents=True, exist_ok=True)

        self._write_pbip_file()
        self._write_pbism_file()
        self._write_model_tmdl(intermediate_model)
        self._write_table_tmdls(intermediate_model)
        self._write_measures_tmdl(dax_conversions)
        self._write_relationships_tmdl(intermediate_model)
        self._write_pbir_file()
        self._write_report_json(intermediate_model)

        logger.info(f"PBIP project generated at: {self.output_dir}")
        return self.output_dir

    def _write_pbip_file(self):
        pbip = {
            "version": "1.0",
            "artifacts": [{"report": {"path": f"{self.project_name}.Report"}}],
            "settings": {"enableAutoRecovery": True},
        }
        (self.output_dir / f"{self.project_name}.pbip").write_text(
            json.dumps(pbip, indent=2), encoding="utf-8"
        )

    def _write_pbism_file(self):
        pbism = {"version": "4.0"}
        (self.semantic_dir.parent / "definition.pbism").write_text(
            json.dumps(pbism, indent=2), encoding="utf-8"
        )

    def _write_model_tmdl(self, model: Dict[str, Any]):
        source_type = model.get("_meta", {}).get("source_type", "thoughtspot")
        tmdl = (
            f"/// Semantic Model — Migrated from ThoughtSpot\n"
            f"/// Generated by ThoughtSpot-to-PowerBI Migration Tool\n"
            f"model Model\n"
            f"    culture: en-US\n"
            f"    defaultPowerBIDataSourceVersion: powerBI_V3\n"
            f"    sourceQueryCulture: en-US\n"
            f"    annotation __TsMigration = '{source_type}'\n"
        )
        (self.semantic_dir / "model.tmdl").write_text(tmdl, encoding="utf-8")

    def _clean_column_name(self, col_name: str) -> str:
        if not col_name:
            return ""
        return re.sub(r"[%\(\)#\$@/\-]", "", col_name).strip()

    def _write_table_tmdls(self, model: Dict[str, Any]):
        for table in model.get("tables", []):
            table_name = table.get("name", "Unknown")
            safe_name = re.sub(r"[^\w\-]", "_", table_name)

            lines = [
                f"/// Table: {table_name}",
                f"/// Source: {table.get('database', '')}.{table.get('schema', '')}.{table.get('source', '')}",
                f"table '{table_name}'",
                "",
            ]

            for col in table.get("column_details", []):
                col_name = col.get("name", "")
                ts_type = col.get("data_type", "VARCHAR")
                pbi_type = self.DATA_TYPE_MAP.get(ts_type.upper() if ts_type else "", "string")
                clean_name = self._clean_column_name(col_name)

                lines.append(f"    column '{clean_name}'")
                lines.append(f"        dataType: {pbi_type}")
                lines.append(f"        sourceColumn: {col.get('db_column_name', col_name)}")

                if col.get("format_pattern"):
                    lines.append(f"        formatString: {col['format_pattern']}")

                if col.get("column_type") == "MEASURE":
                    raw_agg = (col.get("aggregation") or "sum").lower()
                    agg = self.AGGREGATION_MAP.get(raw_agg, "sum")
                    lines.append(f"        summarizeBy: {agg}")
                else:
                    lines.append(f"        summarizeBy: none")

                lines.append("")

            # Power BI requires at least one partition per table
            lines.append(f"    partition '{table_name}' = m")
            lines.append(f"        mode: import")
            lines.append(f"        source =")
            lines.append(f"            let")
            lines.append(f"                Source = Sql.Database(\"{table.get('database', 'Unknown')}\", \"{table.get('schema', 'Unknown')}\")")
            lines.append(f"            in")
            lines.append(f"                Source")
            lines.append("")

            (self.tables_dir / f"{safe_name}.tmdl").write_text("\n".join(lines), encoding="utf-8")

    def _write_measures_tmdl(self, conversions: List[Dict[str, Any]]):
        lines = [
            "/// Measures Table — All converted DAX measures",
            "/// Migrated from ThoughtSpot formulas",
            "table '_Measures'",
            "",
            "    partition '_Measures' = calculated",
            "        mode: import",
            "        source = Row(\"Column\", BLANK())",
            "",
        ]

        # Deduplicate measures by name — keep the first (highest confidence) version
        seen_names: Dict[str, bool] = {}
        unique_conversions = []
        for conv in conversions:
            mname = conv.get("measure_name", "")
            if mname not in seen_names:
                seen_names[mname] = True
                unique_conversions.append(conv)

        for conv in unique_conversions:
            measure_name = conv.get("measure_name", "")
            dax = conv.get("dax_formula", "")
            original = conv.get("original_formula", "")
            confidence = conv.get("confidence", 0)

            # Skip empty / comment-only DAX
            if not dax or dax.startswith("--"):
                continue

            # Extract expression part (after "Name = ")
            # Only strip the "MeasureName = " prefix if it exactly matches the measure name
            # to avoid incorrectly cutting DAX filter expressions that contain comparison " = " operators.
            eq_pos = dax.find(" = ")
            if eq_pos >= 0:
                left_part = dax[:eq_pos].strip()
                clean_left = left_part.strip("'\"[]")
                if clean_left == measure_name:
                    dax_expr = dax[eq_pos + 3:].strip()
                else:
                    dax_expr = dax
            else:
                dax_expr = dax

            # Remove any leading comment lines from the expression
            expr_lines = dax_expr.split("\n")
            expr_lines = [l for l in expr_lines if not l.strip().startswith("--")]
            dax_expr = "\n".join(expr_lines).strip()

            if not dax_expr:
                continue

            lines.append(f"    /// ThoughtSpot: {original}")
            lines.append(f"    /// Confidence: {confidence:.0%}")

            if "\n" in dax_expr:
                # Multi-line DAX: wrap in TMDL triple-backtick block
                lines.append(f"    measure '{measure_name}' = ```")
                for expr_line in dax_expr.split("\n"):
                    stripped = expr_line.rstrip()
                    if stripped:
                        lines.append(f"        {stripped.lstrip()}")
                    else:
                        lines.append("")
                lines.append(f"        ```")
            else:
                lines.append(f"    measure '{measure_name}' = {dax_expr}")

            if conv.get("format_pattern"):
                lines.append(f"        formatString: {conv['format_pattern']}")

            lines.append("")

        (self.tables_dir / "_Measures.tmdl").write_text("\n".join(lines), encoding="utf-8")

    def _write_relationships_tmdl(self, model: Dict[str, Any]):
        lines = []
        joins = model.get("joins", [])

        for i, join in enumerate(joins):
            card = join.get("cardinality", "many-to-one").lower().replace("_", "-")
            
            left_table = join['left_table']
            left_col = self._clean_column_name(join.get("left_column", ""))
            right_table = join['right_table']
            right_col = self._clean_column_name(join.get("right_column", ""))

            # Skip relationships with empty column references
            if not left_col or not right_col:
                logger.warning(f"Skipping relationship: missing column references")
                continue

            if card in ("one-to-one",):
                from_card, to_card = "one", "one"
            elif card in ("many-to-many",):
                from_card, to_card = "many", "many"
            elif card in ("one-to-many",):
                # Power BI requires the from-cardinality of a relationship to be 'many' (except for one-to-one).
                # We flip the from and to ends to represent this as a many-to-one relationship.
                from_card, to_card = "many", "one"
                left_table, right_table = right_table, left_table
                left_col, right_col = right_col, left_col
            else:  # many-to-one (default)
                from_card, to_card = "many", "one"

            cross_filter = self.CROSSFILTER_MAP.get(join.get("join_type", "LEFT_OUTER"), "oneDirection")
            # Sanitize relationship name — must be valid TMDL identifier (no spaces)
            rel_name = join.get("name") or f"rel_{i + 1}"
            rel_name = re.sub(r"[^\w]", "_", rel_name)

            # Separate relationships with a blank line (but not before the first one)
            if lines:
                lines.append("")

            lines.append(f"relationship {rel_name}")
            lines.append(f"    fromColumn: '{left_table}'.'{left_col}'")
            lines.append(f"    fromCardinality: {from_card}")
            lines.append(f"    toColumn: '{right_table}'.'{right_col}'")
            lines.append(f"    toCardinality: {to_card}")
            lines.append(f"    crossFilteringBehavior: {cross_filter}")
            lines.append(f"    isActive: true")

        (self.semantic_dir / "relationships.tmdl").write_text("\n".join(lines), encoding="utf-8")

    def _write_pbir_file(self):
        pbir = {
            "version": "1.0",
            "datasetReference": {
                "byPath": {"path": f"../{self.project_name}.SemanticModel"},
                "byConnection": None,
            },
        }
        (self.report_dir.parent / "definition.pbir").write_text(
            json.dumps(pbir, indent=2), encoding="utf-8"
        )

    def _write_report_json(self, model: Dict[str, Any]):
        """Generate report.json with pages and visuals mapped from ThoughtSpot worksheets."""
        VISUAL_TYPE_MAP = {
            "bar":       "clusteredColumnChart",
            "line":      "lineChart",
            "area":      "areaChart",
            "pie":       "pieChart",
            "donut":     "donutChart",
            "circle":    "scatterChart",
            "text":      "card",
            "map":       "map",
            "square":    "treemap",
            "funnel":    "funnel",
            "waterfall": "waterfallChart",
            "automatic": "clusteredColumnChart",
        }

        worksheets = model.get("worksheets", [])
        visuals_per_page = 6
        pages = []

        # Build pages: 6 visuals per page in a 3-column grid
        for page_idx in range(0, max(len(worksheets), 1), visuals_per_page):
            page_worksheets = worksheets[page_idx : page_idx + visuals_per_page]
            visuals = []

            for i, ws in enumerate(page_worksheets):
                mark = ws.get("mark_type", "automatic")
                visual_type = VISUAL_TYPE_MAP.get(mark, "clusteredColumnChart")

                # 3-column grid layout
                col = i % 3
                row = i // 3
                x = 20 + col * 430
                y = 20 + row * 340

                visuals.append({
                    "name": f"visual_{page_idx + i}",
                    "title": ws.get("title") or ws.get("name", ""),
                    "visualType": visual_type,
                    "position": {
                        "x": x, "y": y,
                        "width": 410, "height": 310,
                    },
                    "dataRoles": {
                        "category": ws.get("cols", []),
                        "values":   ws.get("rows", []),
                    },
                    "note": f"Migrated from ThoughtSpot ({ws.get('ts_chart_type', 'UNKNOWN')})",
                })

            page_num = page_idx // visuals_per_page + 1
            pages.append({
                "name": f"Page {page_num}",
                "displayName": f"Page {page_num}",
                "visuals": visuals,
            })

        # Always ensure at least one page
        if not pages:
            pages.append({
                "name": "Page 1",
                "displayName": "Page 1",
                "visuals": [],
            })

        report = {
            "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/1.0.0/schema.json",
            "themeCollection": {
                "baseTheme": {
                    "name": "CY24SU06",
                    "reportVersionAtImport": "5.55",
                    "type": "SharedResources",
                },
            },
            "pages": pages,
        }
        (self.report_dir / "report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
        logger.info(f"report.json generated with {len(pages)} page(s) and {len(worksheets)} visual(s)")

